### PR TITLE
UIREC-388 Leverage new endpoint to get items across tenants

### PR DESCRIPTION
**Pull request by usavkov-epam**
## Purpose

https://folio-org.atlassian.net/browse/UIREC-388

Use new endpoint to get items to display in the "Bound items" accordion

## Pre-Merge Checklist
Before merging this PR, please go through the following list and take appropriate actions.
- [x] I've added appropriate record to the CHANGELOG.md
- Does this PR meet or exceed the expected quality standards?
  - [x] Code coverage on new code is 80% or greater
  - [x] Duplications on new code is 3% or less
  - [x] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] If any API-related changes - okapi interfaces and permissions are reviewed/changed correspondingly
  - [x] There are no breaking changes in this PR.

If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

### CODE REVIEW

**Review by zburke — CHANGES_REQUESTED** [review]
What interface/version will this new endpoint be a part of? It appears the new endpoint was [added yesterday](https://github.com/folio-org/mod-inventory/pull/755) without bumping the interface up from 13.1 (whoops). Once that gets fixed, then this new functionality needs to be wrapped with `stripes.hasInterface("inventory", "13.2")` or you need to bump the major version and change the `okapiInterface` dependency for `inventory` to `13.2`.

**Comment by usavkov-epam** [comment]
^^ @SerhiiNosko

**Review by SKarolFolio — APPROVED** [review]

**Review by SerhiiNosko — APPROVED** [review]

**Review by alisher-epam — APPROVED** [review]

**Comment by usavkov-epam** [comment]
Hi @zburke, could you please re-review the changes related to your comment?

**Review by zburke — APPROVED** [review]
LGTM

**Pull request merged**
